require:
  - rubocop-rake

AllCops:
  Include:
    - Gemfile
    - '**/*.rb'
  NewCops: enable

Metrics/AbcSize:
  CountRepeatedAttributes: false

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
